#! /bin/bash

# Variable

# Local variable

##################################################################
##################################################################

# Functions

function buildVoltdb(){
local VOLTDB=$dir_local/sources/voltdb
cd $VOLTDB;
ant clean && ant;
}

function buildQuicksort(){
local QUICKSORT=$dir_local/sources/cfm/quicksort
cd $QUICKSORT;
make quicksort;
}

function buildFromDriver(){
buildVoltdb;
buildQuicksort;
}

##################################################################
##################################################################

# Execution
buildFromDriver;
