#! /bin/bash

# Variable

# Local Variable
list_file=("dAerospike" "dSpark" "dScala" "dYcsb" "dGraphx")


# Global Variable

##########################################################
##########################################################

# Functions

# External binaries
# Aerospike
function dAerospike(){
	if [ ! -f "${dir_local_sources}/aerospike.rpm" ]
	then
	  wget -O ${dir_local_sources}/aerospike.rpm https://github.com/aerospike/aerospike-server/releases/download/6.2.0.2/aerospike-server-community-6.2.0.2-1.el8.x86_64.rpm
	  sudo rpm -Uvh ${dir_local_sources}/aerospike.rpm && rm ${dir_local_sources}/aerospike.rpm
	fi
}
# Apache Saprk
function dSpark(){
	if [ ! -f "${dir_local_sources}/spark.tgz" ]
	then
	  wget -O ${dir_local_sources}/spark.tgz https://downloads.apache.org/spark/spark-3.3.2/spark-3.3.2-bin-hadoop3.tgz
	  tar -xzvf ${dir_local_sources}/spark.tgz -C ${dir_local_sources}/
	fi
}
# YCSB
function dYcsb(){
  if [ ! -d $dir_local/sources/ycsb-0.17.0 ]; then
    cd ${dir_local_sources}
    wget https://github.com/brianfrankcooper/YCSB/releases/download/0.17.0/ycsb-0.17.0.tar.gz
    tar -xzvf ycsb-0.17.0.tar.gz
  fi
}

# External dependencies
# Scala
function dScala(){
	if [ ! -f ${dir_local_deps}/scala.rpm ]
	then
	  wget -O ${dir_local_deps}/scala.rpm https://downloads.lightbend.com/scala/2.12.17/scala-2.12.17.rpm
	  sudo rpm -Uvh ${dir_local_deps}/scala.rpm && rm ${dir_local_deps}/scala.rpm
	fi
}

# External datasets
# GrpahX
function dGraphx(){
	if [ ! -d ${dir_local_sources}/spark-3.3.2-bin-hadoop3/ ]
	then
		echo "Spark setup must be preceded."
		echo "Consider carrying out 'make spark graphx' first."
		exit;
	fi

	if [ ! -f ${dir_local_datasets}/graphx_datasets.lnk/soc-LiveJournal1.txt ]
	then
		wget -P ${dir_local_datasets}/graphx_datasets.lnk/ http://snap.stanford.edu/data/soc-LiveJournal1.txt.gz
		gunzip ${dir_local_datasets}/graphx_datasets.lnk/soc-LiveJournal1.txt.gz;
	else
		echo "Dataset already exists."
	fi
}

##################################################################
##################################################################

# Execution

if [ $# -eq 0 ]
then
	for arg in "${list_file[@]}"
	do
#	  if [ "$arg" == "dSpark" ]; then continue; fi
	  $arg
	done
else
	for arg in "$@"
	do
	  d$arg
	done
fi
