#! /bin/bash

# Local variable

# Global variable
export dir_local=/home/$USER/workload-kkc # Default path
export dir_local_conf=$dir_local/conf
export dir_local_datasets=$dir_local/datasets/
export dir_local_deps=$dir_local/deps/
export dir_local_docs=$dir_local/docs/
export dir_local_env=$dir_local/env
export dir_local_evaluation=$dir_local/evaluation/
export dir_local_scripts=$dir_local/scripts/
export dir_local_scripts2=$dir_local/scripts2/
export dir_local_sources=$dir_local/sources/
export dir_local_temp=$dir_local/temp/

##################################################################
##################################################################

# Functions

function getEnv(){
bash ${dir_local}/env/env.sh
}

function runFromDriver(){
  local service_name=$1; shift
  bash ${dir_local}/scripts/run_${service_name}.sh ${*}
}
function printUsage(){
  echo "Usage: $0 <init | build | run>"
  echo "init: Resolve git submodules, packages, binaries"
  echo "build: Build every sources to be runnable"
  echo "run: Execute script to test workload"
}
function printUsageRun(){
  echo "ERROR: '$0 run' requires 1 argument at least"
  echo "Usage: $0 run <workload> [options]"
}

##################################################################
##################################################################

# Execution

#getEnv;

case $1 in
init)
  bash init_from_driver;
  ;;
build)
  bash build_from_driver;
  ;;
run)
  if [ $# -eq 1 ]; then
    printUsageRun;  
  else
    sudo bash -c "echo 3 > /proc/sys/vm/drop_caches"
    shift;
    runFromDriver $*;
  fi
  ;;
*)
  printUsage;
  ;;
esac
