#! /bin/bash

# Local variable

# Global variable
export dir_local=/home/$USER/workload-kkc # Default path
export dir_local_datasets=$dir_local/datasets/
export dir_local_deps=$dir_local/deps/
export dir_local_docs=$dir_local/docs/
export dir_local_evaluation=$dir_local/evaluation/
export dir_local_scripts=$dir_local/scripts/
export dir_local_scripts2=$dir_local/scripts2/
export dir_local_sources=$dir_local/sources/
export dir_local_temp=$dir_local/temp/

##################################################################
##################################################################

# Functions

function checkInstalled(){
  local path_csv=$dir_local_sources/installed_local.csv
  cat "$path_csv" | cut -d',' -f 1- | tr ',' '\t' | column -t

  local count=1
  while IFS=',' read -r field1 field2 field3 field4
  do
    if [[ $count -gt 1 ]]; then
      local var_name="$field1"
      local var_flag="$field2"
#      echo "var_flag: $var_flag"
      
#     if [ "$var_flag" -eq 0 ]; then
#	echo "$var_name is not installed."
#     else
#	echo "$var_name is installed."
#     fi
      
    fi
    ((count++))
  done < "$path_csv"
}

##################################################################
##################################################################

# Execution

checkInstalled;
